#see more variables at https://gohugo.io/overview/configuration/#configuration-variables

# hostname (and path) to the root eg. http://spf13.com/
baseurl = "/"

# Site title
title = "CosmicBagel"

noTimes = "false"

# Copyright
copyright = "(c) 2021 CosmicBagel"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "bagelwave"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
#disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    #tag = "tags"
    topic = "topics"

[author]
    name="Samuel Whiteley"
    email="sam@cosmicbagel.com"

#these params are for the theme
[params]
    # you can use markdown here
    brand = "CosmicBagel"
    topline = "Samuel Whiteley"
    footline = ""

    #Sidebar position
    #false, true, "left", "right"
    sidebar = "left"

    #Page navigation
    isPageNavOn = false

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "portfolio"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    github = "CosmicBagel" # Your Github profile ID
    #bitbucket = "" # Your Bitbucket profile ID
    linkedin = "snwhiteley" # Your LinkedIn profile ID (from public URL)
    #googleplus = "" # Your Google+ profile ID
    #facebook = "" # Your Facebook profile ID
    #twitter = "" # Your Twitter profile ID
    #youtube = ""  # Your Youtube channel ID
    #flattr = ""  # populate with your flattr uid
    #flickr = "" # Your Flickr profile ID
    #vimeo = "" # Your Vimeo profile ID
    #soundcloud = "cosmic-bagel"

    #Newsletter / email subscription link
    #newsletter = "http://eepurl.com/ghpyyT"

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rssTruncateEnabled = true
    rssDescriptionLength = 350
    rss = true

    #Google analytics
    googleAnalytics = "UA-12789702-1"

    description = "The rarely updated blog of Samuel N. Whiteley"

    isCommentsOn = false